# Generated by Django 2.2 on 2020-12-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0004_sewa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='intstalasi',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='jabatan',
        ),
        migrations.AddField(
            model_name='sewa',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='sewa',
            name='tanggal_mulai',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sewa',
            name='tanggal_selesai',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sewa',
            name='titik_penjemputan',
            field=models.TextField(default=False, max_length=254),
        ),
    ]
