# Generated by Django 2.2 on 2020-12-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0005_auto_20201218_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewa',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sewa',
            name='titik_penjemputan',
            field=models.TextField(max_length=254),
        ),
    ]
