# Generated by Django 2.2 on 2020-12-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0010_auto_20201218_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewa',
            name='no_hp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sewa',
            name='no_ktp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
