# Generated by Django 2.2 on 2020-12-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0018_remove_images_image_utama'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='t_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
