# Generated by Django 2.2 on 2020-12-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0019_images_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='t_id',
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pengguna.DataBus'),
        ),
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi_asal', models.CharField(default=None, max_length=100)),
                ('kabupaten_asal', models.CharField(default=None, max_length=100)),
                ('provinsi_tujuan', models.CharField(default=None, max_length=100)),
                ('kabupaten_tujuan', models.CharField(default=None, max_length=100)),
                ('harga', models.IntegerField(default=500000)),
                ('nama', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='biaya', to='pengguna.DataBus')),
            ],
        ),
    ]
