# Generated by Django 2.2 on 2021-01-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0025_auto_20210105_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='no_plat',
        ),
    ]
