# Generated by Django 2.2 on 2021-01-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0029_auto_20210107_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ketersediaan',
            old_name='sedia',
            new_name='id_bus',
        ),
    ]
