# Generated by Django 2.2 on 2021-01-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0030_auto_20210107_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketersediaan',
            name='id_bus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_bus', to='pengguna.DataBus'),
        ),
    ]
