# Generated by Django 2.2 on 2021-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0031_auto_20210107_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketersediaan',
            name='id_bus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
